"""
Qubot Load Tests — Locust

Run with:
    locust -f tests/load/locustfile.py --host http://localhost:8000

Web UI at http://localhost:8089
Target: 100 concurrent users, P95 < 500ms
"""

import json
import random

from locust import HttpUser, between, task


# ── Shared test credentials ────────────────────────────────────────────────

_REGISTERED: list[dict] = []


def _register_user(client) -> dict | None:
    """Register a unique user and return credentials."""
    n = random.randint(1, 9_999_999)
    payload = {
        "email": f"loadtest{n}@qubot.io",
        "username": f"loaduser{n}",
        "password": "LoadTest123!",
    }
    resp = client.post("/api/v1/auth/register", json=payload, name="/auth/register")
    if resp.status_code in (200, 201):
        return payload
    return None


def _login(client, email: str, password: str) -> str | None:
    """Login and return access_token."""
    resp = client.post(
        "/api/v1/auth/login",
        json={"email": email, "password": password},
        name="/auth/login",
    )
    if resp.status_code == 200:
        return resp.json().get("access_token")
    return None


# ── User classes ───────────────────────────────────────────────────────────

class ReadOnlyUser(HttpUser):
    """
    Simulates a dashboard viewer — reads agents, tasks, metrics.
    High frequency, no writes.
    """

    wait_time = between(0.5, 2)

    def on_start(self):
        creds = _register_user(self.client)
        if creds:
            token = _login(self.client, creds["email"], creds["password"])
            self.headers = {"Authorization": f"Bearer {token}"} if token else {}
        else:
            self.headers = {}

    @task(5)
    def list_agents(self):
        self.client.get(
            "/api/v1/agents?limit=20",
            headers=self.headers,
            name="/agents (list)",
        )

    @task(5)
    def list_tasks(self):
        self.client.get(
            "/api/v1/tasks?limit=20",
            headers=self.headers,
            name="/tasks (list)",
        )

    @task(3)
    def kanban_board(self):
        self.client.get(
            "/api/v1/tasks/kanban/board",
            headers=self.headers,
            name="/tasks/kanban/board",
        )

    @task(2)
    def health_check(self):
        self.client.get("/api/v1/health", name="/health")

    @task(1)
    def list_tools(self):
        self.client.get(
            "/api/v1/tools?limit=20",
            headers=self.headers,
            name="/tools (list)",
        )


class WriteUser(HttpUser):
    """
    Simulates an active operator — creates and updates tasks, sends chat messages.
    Lower frequency than reads.
    """

    wait_time = between(2, 5)

    def on_start(self):
        creds = _register_user(self.client)
        if creds:
            token = _login(self.client, creds["email"], creds["password"])
            self.headers = {"Authorization": f"Bearer {token}"} if token else {}
        else:
            self.headers = {}
        self._task_ids: list[str] = []

    @task(3)
    def create_task(self):
        n = random.randint(1, 99999)
        resp = self.client.post(
            "/api/v1/tasks",
            json={
                "title": f"Load test task {n}",
                "description": "Generated by Locust",
                "priority": random.choice(["LOW", "MEDIUM", "HIGH"]),
                "status": "BACKLOG",
            },
            headers=self.headers,
            name="/tasks (create)",
        )
        if resp.status_code in (200, 201):
            task_id = resp.json().get("data", {}).get("id") or resp.json().get("id")
            if task_id:
                self._task_ids.append(task_id)

    @task(2)
    def update_task_status(self):
        if not self._task_ids:
            return
        task_id = random.choice(self._task_ids)
        self.client.patch(
            f"/api/v1/tasks/{task_id}/status",
            json={"status": random.choice(["BACKLOG", "IN_PROGRESS", "DONE"])},
            headers=self.headers,
            name="/tasks/:id/status (update)",
        )

    @task(2)
    def send_chat_message(self):
        messages = [
            "Create a task to review the quarterly report",
            "What are the active agents right now?",
            "Show me pending tasks",
            "Assign the security audit to the backend agent",
        ]
        self.client.post(
            "/api/v1/chat",
            json={"message": random.choice(messages)},
            headers=self.headers,
            name="/chat (send)",
        )

    @task(1)
    def list_my_tasks(self):
        self.client.get(
            "/api/v1/tasks?status=IN_PROGRESS&limit=10",
            headers=self.headers,
            name="/tasks?status=IN_PROGRESS",
        )


class AuthStressUser(HttpUser):
    """
    Stress tests the auth endpoints specifically.
    Low weight — just enough to verify rate limiting doesn't break real users.
    """

    wait_time = between(5, 10)
    weight = 1  # Much fewer of these than ReadOnly/Write users

    @task
    def login_logout_cycle(self):
        creds = _register_user(self.client)
        if not creds:
            return
        token = _login(self.client, creds["email"], creds["password"])
        if token:
            self.client.post(
                "/api/v1/auth/logout",
                headers={"Authorization": f"Bearer {token}"},
                name="/auth/logout",
            )
